window.Templates = {}
window.Templates["register"] = "<form id=\"register\">\n  <h2>Register</h2>\n  <p>\n    Registration is free and only takes a few seconds.\n  <p>\n  Name: <input type='text' name='forename' placeholder='First Name'/><input type='text' name='surname' placeholder='Last Name'/><br/>\n  Username: <input type='text' name='username'/><br/>\n  Password: <input type='password' name='password'/><br/>\n  Password (Repeat): <input type='password' name='password-repeat'/><br/>\n  <input type=\"submit\" value=\"register\">\n</form>\n";
window.Templates["search_results"] = "{{#has_results}}<hr/>{{/has_results}}\n<h3>Users</h3>\n{{#users}}\n<div class='search-user'>\n    {{ forename }} {{ surname }} (<a href='#/user/{{ username }}'>@{{ username }}</a>)\n</div>\n{{/users}}\n<h3>Polls</h3>\n{{#polls}}\n<div class='poll-tiny'>\n    <span class='name'><a href='#/poll/{{ id }}'>{{ name }}</a></span>\n    <span class='description'>{{ description }}</span>\n</div>\n{{/polls}}\n";
window.Templates["poll"] = "<div id='poll'>\n  {{#editable}}\n  <div id='poll-panel'>\n    <a href='#/edit-poll/{{ id }}'>edit</a>\n    {{^finalized}}<a href='#/finalize-poll/{{ id }}'>finalize</a>{{/finalized}}\n    <a href='#/delete-poll/{{ id }}'>delete</a>\n  </div>\n  {{/editable}}\n\n  <h2 class='poll-title'>{{ name }}</h2>\n  <span class='meta'>{{ user.forename }} {{ user.surname }} (<a href='#/user/{{user.username}}'>@{{ user.username }}</a>)</span>\n  <p>{{ description }}</p>\n\n  <hr />\n  <div id='votes'>\n  {{^finalized}}\n    {{#votes}}\n      <div class='vote'>\n        {{^voted}}\n          <span class='poll-option not-voted'>{{ name }} ({{ num }})</span>\n          <a class='add-vote' data-id='{{ id }}'>vote</a>\n        {{/voted}}\n        {{#voted}}\n          <span class='poll-option voted'>{{ name }} ({{ num }})</span>\n          <a class='add-unvote' data-id='{{ id }}'>unvote</a>\n        {{/voted}}\n      </div>\n    {{/votes}}\n    {{^votes}}<span class='gray'>no vote options</span>{{/votes}}\n  {{/finalized}}\n  {{#finalized}}\n    {{#votes}}\n      <div class='vote finalized'>\n        <span class='poll-option{{^voted}} not-voted{{/voted}}{{#voted}} voted{{/voted}}'>{{ name }} ({{ num }})</span>\n      </div>\n    {{/votes}}\n    {{^votes}}<span class='gray'>no vote options</span>{{/votes}}\n  {{/finalized}}\n  </div>\n\n  <hr />\n  {{#finalized}}\n  <p id='poll-finalized'>Poll finalized.</p>\n  <hr />\n  {{/finalized}}\n  <form id='comment-box'>\n      <textarea name='text'/>\n      <button class='comment-box-submit'>Reply</button>\n  </form>\n\n  <div id='comments'></div>\n</div>\n";
window.Templates["people"] = "<h2>Users</h2>\n<ul>\n{{#people}}\n  <li>{{ forename }} {{ surname }} (<a href='#/user/{{ username }}'>@{{ username }}</a>)</li>\n{{/people}}\n</ul>\n";
window.Templates["user"] = "<div class='user'>\n  <span class='name'>{{ forename }} {{ surname }} (@{{username}})</span>\n</div>\n\n<h3>Polls Created</h3>\n{{#polls_created}}\n  <div class='poll-tiny'>\n    <span class='name'><a href='#/poll/{{ id }}'>{{ name }}</a></span>\n    <span class='description'>{{ description }}</span>\n  </div>\n{{/polls_created}}\n";
window.Templates["settings"] = "<form id=\"settings\">\n  <h2>Settings</h2>\n  {{#saved}}\n  <span id='settings-saved'>Your changes have been saved.</span>\n  {{/saved}}\n  Name: <input type='text' name='forename' placeholder='First Name' value='{{ forename }}'/><input type='text' name='surname' placeholder='Last Name' value='{{ surname }}'/><br/>\n  Username: <input type='text' name='username' value='{{ username }}'/><br/>\n  Password: <input type='password' name='password'/><br/>\n  Password (Repeat): <input type='password' name='password-repeat'/><br/>\n  <input type=\"submit\" value=\"save\">\n</form>\n";
window.Templates["comment"] = "<div class='comment'>\n  <div class='comment-user'><a href='#/user/{{ user.username }}'>{{ user.forename }} {{ user.surname }}</a>:</div>\n  <div class='comment-text'>{{ text }}</div>\n  <div class='comment-panel' data-comment-id='{{ id }}'>\n    {{#repliable}}<button class='comment-reply'>reply</button>{{/repliable}}\n    {{#deletable}}<button class='comment-delete'>delete</button>{{/deletable}}\n  </div>\n  <div class='comment-children'></div>\n</div>\n";
window.Templates["dashboard"] = "<div class='user'>\n  <span class='name'>{{ forename }} {{ surname }} (@{{username}})</span>\n</div>\n\n<h3>My Polls</h3>\n{{#polls_created}}\n  <div class='poll-tiny'>\n    <span class='name'><a href='#/poll/{{ id }}'>{{ name }}</a></span>\n    <span class='description'>{{ description }}</span>\n  </div>\n{{/polls_created}}\n\n<h3>Participated Polls</h3>\n{{#polls_participated}}\n  <div class='poll-tiny'>\n    <span class='name'><a href='#/poll/{{ id }}'>{{ name }}</a></span>\n    <span class='description'>{{ description }}</span>\n  </div>\n{{/polls_participated}}\n";
window.Templates["search"] = "<div id='search'>\n  <form id='search-form'>\n    <input name='q' type='text' placeholder='Search...' />\n    <input name='include_users' type='checkbox' checked/> Include users<br/>\n    <input name='include_polls' type='checkbox' checked/> Include polls<br/>\n    <input type='submit' value='search' />\n  </form>\n  <div id='results'></div>\n</div>\n";
window.Templates["poll_option"] = "<div data-id='{{ id }}'><input data-id='{{ id }}' value='{{ name }}'/><button class='remove-option'>-</button></div>\n";
window.Templates["navbar"] = "<a href='#/people'>users</a>\n<a href='#/search'>search</a>\n{{#logged_in}}\n<a href='#/create-poll'>create poll</a>\n<a href='#/settings'>settings</a>\n<a href='#/logout'>logout</a>\n{{/logged_in}}\n{{^logged_in}}\n<a href='#/login'>login</a>\n{{/logged_in}}\n";
window.Templates["edit_poll"] = "<div id='edit-poll'>\n  <h3>Basics</h3>\n  Name: <input name='name' value='{{ name }}'><br/>\n  Description:\n  <textarea name='description'>{{ description }}</textarea>\n\n  <h3>Options</h3>\n  <div id='edit-poll-options'></div>\n  <div id='add-poll-options'>\n    <input id='add-poll-option-text' name='add-poll-option'></input><button id='add-option'>add</button>\n  </div>\n\n  <hr/>\n  <button id='save'>save</button>\n  <a href='#/poll/{{ id }}'><button>cancel</button></a>\n</div>\n";
window.Templates["create_poll"] = "<div id='create-poll'>\n  <h2>Create Poll</h2>\n  Name: <input type='text' name='name'/><br/>\n  Description:<br/>\n  <textarea name='description'/><br/>\n  <input type='checkbox' name='multi'> Multi (users can select multiple options)\n  <button id='create'>create</button>\n</div>\n";
window.Templates["login"] = "<form id=\"login\">\n  <h2>Log In</h2>\n  Username: <input type='text' name='username'/><br/>\n  Password: <input type='password' name='password'/><br/>\n  <input type=\"submit\" value=\"log in\">\n  <a id='register' href='#/register'><input type='button' value='register' /></a>\n</form>\n";
